Repository NickNameYouTuber/messenger-app, pull requests merged in 2025-03, with the labels that each got.

#15 Feature/10 create simple frontend
  .github/workflows/create-branch-task.yml
  .github/workflows/main.yml
  .github/workflows/track-status-change.yml
  .idea/workspace.xml
  frontend/world-time-city-tests.js
  frontend/world-time-city-website.html
  test.txt
Labels: frontend

#16 Feature/11 create simple backend
  .gitignore
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/material_theme_project_new.xml
  .idea/messenger-app.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/app.py
  backend/test_main.py
  changelog.md
Labels: documentation, backend

#18 feat: secret
  backend/app.py
Labels: backend

#22 Feature/19 docker
  backend/Dockerfile
  backend/app.py
  backend/requirements.txt
  docker-compose.yml
  file_for_test.txt
  frontend/Dockerfile
  frontend/nginx.conf
Labels: backend, frontend, devops

#24 feature/12_Write_readme update_readme
  README.md
  assets/logo.jpg
Labels: documentation

#38 Feature/test actions
  .github/workflows/ci_cd.yml
  .github/workflows/sonar-analysis.yml
  .github/workflows/sonar-project.yml
  .github/workflows/test.yml
  frontend/app-logic.js
  frontend/app.js
  frontend/package.json
  frontend/world-time-city-website.html
  frontend/world-time-city.test.js
Labels: documentation, devops

#40 Feature devops/31 auto version
  .github/scripts/version_up.py
  .github/workflows/version.yml
  .gitignore
Labels: devops

#43 Feature/test actions
  .github/scripts/version_up.py
  .github/workflows/ci_cd.yml
  .github/workflows/version.yml
  test.txt
Labels: documentation, devops

#44 Develop
  .github/scripts/version_up.py
  .github/workflows/ci_cd.yml
  .github/workflows/sonar-project.properties
  .github/workflows/sonar-project.yml
  .github/workflows/version.yml
  test.txt
Labels: documentation, backend, frontend, devops

#45 fix yml
  .github/workflows/ci_cd.yml
Labels: devops, fix

#46 Develop
  .github/workflows/ci_cd.yml
Labels: devops, fix

#47 Feature/test workflows
  .github/workflows/ci_cd.yml
  .github/workflows/sonar-analysis.yml
  .github/workflows/sonar-project.properties
  sonar-project.properties
Labels: devops

#48 Develop
  .github/workflows/ci_cd.yml
  .github/workflows/sonar-analysis.yml
  .github/workflows/sonar-project.properties
  sonar-project.properties
Labels: devops

#50 Feature/test workflows (#49)
  .github/workflows/ci_cd.yml
  .github/workflows/version.yml
  .last_commit
  changelog.md
  test.txt
  version/version
  version/version_log
Labels: devops, fix

#54 Develop
  .github/workflows/ci_cd.yml
Labels: frontend, devops, fix, test-passed

#58 deploy
  .github/workflows/deploy.yml
  frontend/nginx.conf
  frontend/public/index.html
Labels: devops

#59 Update deploy.yml
  .github/workflows/deploy.yml
Labels: devops

#60 Update CitySearch.js
  frontend/src/components/CitySearch.js
Labels: frontend, devops

#63 Feature/k8s
  .github/workflows/deploy.yml
  .last_commit
  changelog.md
  kubernetes-deployment.yaml
  version/version
  version/version_log
Labels: devops

#64 Develop
  .github/workflows/ci_cd.yml
  .github/workflows/deploy.yml
  .last_commit
  changelog.md
  kubernetes-deployment.yaml
  version/version
  version/version_log
Labels: devops

#65 Update deploy.yml
  .github/workflows/deploy.yml
Labels: devops
